# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'application_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ApplicationDialog(object):
    def setupUi(self, ApplicationDialog):
        ApplicationDialog.setObjectName("ApplicationDialog")
        ApplicationDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(ApplicationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelCompany = QtWidgets.QLabel(ApplicationDialog)
        self.labelCompany.setObjectName("labelCompany")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelCompany)
        self.company_input = QtWidgets.QLineEdit(ApplicationDialog)
        self.company_input.setObjectName("company_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.company_input)
        self.labelJobName = QtWidgets.QLabel(ApplicationDialog)
        self.labelJobName.setObjectName("labelJobName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelJobName)
        self.jobName_input = QtWidgets.QLineEdit(ApplicationDialog)
        self.jobName_input.setObjectName("jobName_input")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.jobName_input)
        self.labelDate = QtWidgets.QLabel(ApplicationDialog)
        self.labelDate.setObjectName("labelDate")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelDate)
        self.date_input = QtWidgets.QDateEdit(ApplicationDialog)
        self.date_input.setCalendarPopup(True)
        self.date_input.setObjectName("date_input")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.date_input)
        self.labelLink = QtWidgets.QLabel(ApplicationDialog)
        self.labelLink.setObjectName("labelLink")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelLink)
        self.link_input = QtWidgets.QLineEdit(ApplicationDialog)
        self.link_input.setObjectName("link_input")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.link_input)
        self.labelStatus = QtWidgets.QLabel(ApplicationDialog)
        self.labelStatus.setObjectName("labelStatus")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelStatus)
        self.status_input = QtWidgets.QComboBox(ApplicationDialog)
        self.status_input.setObjectName("status_input")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.status_input)
        self.labelComment = QtWidgets.QLabel(ApplicationDialog)
        self.labelComment.setObjectName("labelComment")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelComment)
        self.comment_input = QtWidgets.QTextEdit(ApplicationDialog)
        self.comment_input.setObjectName("comment_input")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.comment_input)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(ApplicationDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ApplicationDialog)
        QtCore.QMetaObject.connectSlotsByName(ApplicationDialog)

    def retranslateUi(self, ApplicationDialog):
        _translate = QtCore.QCoreApplication.translate
        ApplicationDialog.setWindowTitle(_translate("ApplicationDialog", "Application"))
        self.labelCompany.setText(_translate("ApplicationDialog", "Company:"))
        self.labelJobName.setText(_translate("ApplicationDialog", "Job Name:"))
        self.labelDate.setText(_translate("ApplicationDialog", "Date:"))
        self.labelLink.setText(_translate("ApplicationDialog", "Link:"))
        self.labelStatus.setText(_translate("ApplicationDialog", "Status:"))
        self.labelComment.setText(_translate("ApplicationDialog", "Comment:"))
